### Problem 2: Display the first 5 rows of the NumPy array.

In [5]:
import numpy as np
data = np.loadtxt("./dataset.csv", delimiter=",", skiprows=1)
print(data[0:5])

[[ 0.79741696 -0.95809082  1.49014782  2.27794226]
 [ 0.02683818 -0.24417831  2.15153479 -3.39535586]
 [ 0.19999    -1.01479874  1.41061311 -3.07074603]
 [ 0.47412449  0.44804015  0.63509089 -0.24626915]
 [ 0.59851645  0.08783925  0.39210432  3.21508647]]
