### Problem 16: Filter rows based on multiple conditions (e.g., col1 > 50 and col2 < 100).

In [9]:
import numpy as np
data = np.loadtxt("./dataset.csv",delimiter=",",skiprows=1)
filtered_data = data[(data[:,0]>0.1) & (data[:,1]<0) & (data[:,2]>5)]
print(filtered_data.shape)
print(filtered_data)

(14, 4)
[[ 0.77837395 -0.35047988  5.22959296 -0.95718769]
 [ 0.11430505 -0.15910325  6.36146396 -0.1593781 ]
 [ 0.96630406 -0.76705131  5.71446493  0.75862207]
 [ 0.25018253 -0.13492071  5.04695081 -0.65062303]
 [ 0.54529796 -2.49706472  7.73418245  0.30791673]
 [ 0.39520562 -0.62359331  7.66631597 -1.78937815]
 [ 0.330027   -1.03340965  5.07035158 -2.32791432]
 [ 0.35973202 -0.69661988  6.2039439   2.53211275]
 [ 0.73027356 -0.08660863  7.47962611 -1.12092248]
 [ 0.60108185 -1.22298301  6.12819829  0.09184572]
 [ 0.50893067 -1.70809564  5.1154841   0.67063811]
 [ 0.51105647 -0.46240141  5.23414851  0.94742211]
 [ 0.3841498  -0.78092702  7.45550803  0.94782679]
 [ 0.72407385 -0.46870682  5.3221227  -2.6977062 ]]
