### Problem 12: Standardize a numerical column.

In [4]:
import numpy as np
data = np.loadtxt("./dataset.csv",delimiter=",",skiprows=1)
# Column 0
col0 = data[:,0]
mean = np.mean(col0)
std = np.std(col0)
standardized_col0 = (data[:,0] - mean) / std
print(standardized_col0)

[ 0.89184724 -1.49792961 -0.96093816 ... -0.7645974   0.40671048
  1.21485476]


In [5]:
# If want to standardize all columns at once

means = np.mean(data, axis=0)
stds = np.std(data, axis=0)

standardized_data = (data - means) / stds
print(standardized_data)

[[ 0.89184724 -0.93904274  0.50094197  1.25833   ]
 [-1.49792961 -0.23264511  1.16818584 -1.84218465]
 [-0.96093816 -0.99515373  0.42070295 -1.66478211]
 ...
 [-0.7645974   0.98529837  0.33620097  0.95377562]
 [ 0.40671048 -1.17825395 -0.68738094 -1.80138655]
 [ 1.21485476  1.82601442  1.10354507 -0.12825906]]
