### Problem 8: Sort the NumPy array based on a specific numerical column.

In [4]:
import numpy as np
data = np.loadtxt("./dataset.csv",delimiter=",",skiprows=1)
#Sorting by Column 1 (0 indexed)
sorted_data = data[data[:, 1].argsort()]
sorted_data_desc = data[data[:, 1].argsort()[::-1]]
# Why this works
# data[:, 1] → selects column 1
# .argsort() → returns indices that would sort this column
# data[...] → reorders rows using those indices
print(sorted_data)
print("###############################################################################")
print(sorted_data_desc)

[[ 0.31716873 -3.64431605  1.22740085 -0.93427949]
 [ 0.28525646 -3.42992257  0.9294952   0.45814192]
 [ 0.17997779 -3.34256686  1.95683769  0.13634077]
 ...
 [ 0.32904719  3.0119481   0.27780782  0.39576579]
 [ 0.48150509  3.0276676   1.42395767  3.60003269]
 [ 0.37858294  3.42206188  0.09153923 -2.04599715]]
###############################################################################
[[ 0.37858294  3.42206188  0.09153923 -2.04599715]
 [ 0.48150509  3.0276676   1.42395767  3.60003269]
 [ 0.32904719  3.0119481   0.27780782  0.39576579]
 ...
 [ 0.17997779 -3.34256686  1.95683769  0.13634077]
 [ 0.28525646 -3.42992257  0.9294952   0.45814192]
 [ 0.31716873 -3.64431605  1.22740085 -0.93427949]]
