### Problem 9: Select rows where a numerical column value is greater than a given threshold.

In [15]:
import numpy as np
threshold = 0.1
data = np.loadtxt("./dataset.csv",delimiter=",",skiprows=1)
# Taking Column 0
# filtered_data = data[data[:, 0] > threshold]

filtered_data = []
for row in data:
    if row[0]>threshold:
        filtered_data.append(list(row))
filtered_data = np.array(filtered_data)

print(filtered_data)

[[ 0.79741696 -0.95809082  1.49014782  2.27794226]
 [ 0.19999    -1.01479874  1.41061311 -3.07074603]
 [ 0.47412449  0.44804015  0.63509089 -0.24626915]
 ...
 [ 0.26329969  0.98672203  1.32685287  1.72067098]
 [ 0.64098558 -1.19984684  0.3122557  -3.3207038 ]
 [ 0.90157009  1.83638189  2.08746142 -0.25922785]]
