### Problem 11: Normalize a numerical column to have values between 0 and 1.

In [ ]:
import numpy as np
data = np.loadtxt("./dataset.csv",delimiter=",",skiprows=1)
# Column 0
# col0 = data[:,0]
# mx = max(col0)
# mn = min(col0)
# for i in range(data.shape[0]):
#     data[i:i+1,0:1] = (mx-data[i:i+1,0:1])/(mx-mn)

# Column 0
col0 = data[:, 0]
mx = np.max(col0)
mn = np.min(col0)

# Normalize column 0: (mx - value) / (mx - mn)
data[:, 0] = (mx - col0) / (mx - mn)
print(data)


[[ 0.35482605 -0.95809082  1.49014782  2.27794226]
 [ 0.74510388 -0.24417831  2.15153479 -3.39535586]
 [ 0.65740705 -1.01479874  1.41061311 -3.07074603]
 ...
 [ 0.62534236  0.98672203  1.32685287  1.72067098]
 [ 0.43405442 -1.19984684  0.3122557  -3.3207038 ]
 [ 0.30207523  1.83638189  2.08746142 -0.25922785]]
