### Problem 1: Load the dataset into a NumPy array from a CSV file.

In [2]:
import numpy as np
data = np.loadtxt("./dataset.csv", delimiter=",", skiprows=1)
print(data)

[[ 0.79741696 -0.95809082  1.49014782  2.27794226]
 [ 0.02683818 -0.24417831  2.15153479 -3.39535586]
 [ 0.19999    -1.01479874  1.41061311 -3.07074603]
 ...
 [ 0.26329969  0.98672203  1.32685287  1.72067098]
 [ 0.64098558 -1.19984684  0.3122557  -3.3207038 ]
 [ 0.90157009  1.83638189  2.08746142 -0.25922785]]
