### USED WHEN WE HAVE DIFFERENT SHAPES

In [5]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4])   # Broadcasting means [4,4,4]

print(np.add(a,b))

[5 6 7]


#### Compatibility -> Same or one of them 1

In [ ]:
a = np.array([1,2,3])   # [1,2,3] -> [[1,2,3]] -> [[1,2,3],[1,2,3]]
# a->(3)->(1,3)->(2,3)
b = np.array([[4],[5]]) # [[4],[5]] -> [[4,4,4],[5,5,5]]
# b->(2,1)->(2,3)

# a->(1,3)
# b->(2,1)
# Compatible

# a->(1,3,5,6,1,1,9)
# b->(2,1,5,1,5,7,9)
# Compatible

# a->(1,3,5,6,1,1,9)
# b->(2,1,5,3,5,7,9)
# Not Compatible

print(np.add(a,b))

[[5 6 7]
 [6 7 8]]


In [11]:
a = np.random.random((1,3,5,6,1,1,9))
b = np.random.random((2,1,5,1,5,7,9))

print((np.add(a,b)).shape)
print(np.add(a,b))


(2, 3, 5, 6, 5, 7, 9)
[[[[[[[1.04305638 1.78706642 0.75557235 ... 1.25296163 1.12464812
       1.11387381]
      [0.43931082 1.09967957 0.68853702 ... 1.18001402 1.18383005
       1.37732787]
      [0.99751862 1.34005195 1.19808427 ... 0.82465276 1.29964828
       0.75609532]
      ...
      [0.13925766 1.08097772 1.47155932 ... 0.91044471 0.9063402
       0.81620898]
      [0.64308883 1.64652515 1.36686368 ... 1.24565236 1.40372539
       1.55479363]
      [0.47396701 1.64126086 1.48691499 ... 0.77853429 0.51727528
       1.46846529]]

     [[0.96643132 1.67364545 1.09909685 ... 0.95034592 1.19600712
       1.01657842]
      [0.62254189 1.83426853 0.69775076 ... 0.61438055 0.56221033
       0.81332783]
      [0.71945325 1.73432873 0.91878272 ... 0.72106663 1.13878278
       1.53291064]
      ...
      [1.04158344 1.06174329 0.59822112 ... 0.47055449 1.16718721
       0.87305286]
      [0.33881097 1.8617473  1.29517446 ... 0.67416202 0.76214606
       1.35912539]
      [0.59132227 0.98