In [5]:
import numpy as np

a = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(a[0][1])
print(a[0:2])

2
[[1 2 3]
 [4 5 6]]


In [14]:
print(a[(0,1)])
print("==========================")
print(a[[0,2]])
print("==========================")
print(a[[1]])
print("==========================")


2
[[1 2 3]
 [7 8 9]]
[[4 5 6]]


In [ ]:
print(a[:,:])  # Everything

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print(a[:,1])  # Everything from row and only 2nd column

[2 5 8]


In [18]:
print(a[0:2,1:3])   # Rows -> 0,1   Columns -> 1,2

[[2 3]
 [5 6]]


In [23]:
print(a[0:2,1:3,np.newaxis]) 
print("==========================")
print(a[1,:]) 
print(a[np.newaxis,1,:]) 

[[[2]
  [3]]

 [[5]
  [6]]]
[4 5 6]
[[4 5 6]]


In [34]:
print(a[[0,2]])
print("==========================")
print(a[:,[0,2]])
print("==========================")
print(a[[0,1,2],[0,2,2]])

[[1 2 3]
 [7 8 9]]
[[1 3]
 [4 6]
 [7 9]]
[1 6 9]
