### SORTING

In [8]:
import numpy as np

a = np.array([
    [5,9,8],
    [4,1,6],
    [7,3,2]
])

print(np.sort(a))
print("==========================")
print(a)

[[5 8 9]
 [1 4 6]
 [2 3 7]]
[[5 9 8]
 [4 1 6]
 [7 3 2]]


In [9]:
a.sort()  # a = np.sort(a)
print(a)

[[5 8 9]
 [1 4 6]
 [2 3 7]]


In [10]:
print(np.sort(a,axis=1))

[[5 8 9]
 [1 4 6]
 [2 3 7]]


In [11]:
print(np.sort(a,axis=0))

[[1 3 6]
 [2 4 7]
 [5 8 9]]


In [12]:
print(np.sort(a.flatten()).reshape(a.shape))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### SEARCHING

In [ ]:
outputs = np.array([0.05,0.01,0.87,0.02,0.01,0,0.03,0.01])
print(np.argmax(outputs))   # Index of MAX
print(np.argmin(outputs))   # Index of MIN
print(np.nonzero(outputs))  # Indices of non zero elements

2
5
(array([0, 1, 2, 3, 4, 6, 7], dtype=int64),)


In [24]:
print(np.where(outputs > 0.01, outputs, 0))     # Jaha Jaha 0.01 se bada nahi waha 0

[0.05 0.   0.87 0.02 0.   0.   0.03 0.  ]
