In [2]:
import numpy as np

a = np.arange(12).reshape(3,4)

print(a)

for row in a:
    for item in row:
        print(item, end=" ")
    print()

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
0 1 2 3 
4 5 6 7 
8 9 10 11 


In [3]:
for item in np.nditer(a):
    print(item,end=" ")

0 1 2 3 4 5 6 7 8 9 10 11 

In [4]:
for item in np.nditer(a,order="C"):
    print(item,end=" ")

0 1 2 3 4 5 6 7 8 9 10 11 

In [5]:
for item in np.nditer(a,order="F"):
    print(item,end=" ")

0 4 8 1 5 9 2 6 10 3 7 11 

In [ ]:
for item in np.nditer(a):
    item = item**2  # Nothing changes

print(a) 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [10]:
with np.nditer(a, op_flags=['readwrite']) as it:
    for item in it:
        # item = item**2  # Nothing changes
        item[...] = item ** 2  # modify in place
    
print(a)

[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]
