In [3]:
import numpy as np

arr = np.array([1,2,3,4,5])

new_arr = arr[2:5]

print(new_arr)      # Exactly same data points but different view

new_arr[1] = 100    # Changes in arr also(referenced)

print(new_arr)
print(arr)

[3 4 5]
[  3 100   5]
[  1   2   3 100   5]


In [ ]:
arr2 = arr      # Exactly same again
print(arr2)

arr2[2] = 100

print(arr2)
print(arr)

[  1   2   3 100   5]
[  1   2 100 100   5]
[  1   2 100 100   5]


In [5]:
# For Copying ->
copy = arr.copy()
print(copy)
copy[0] = 100
print(copy)
print(arr)

[  1   2 100 100   5]
[100   2 100 100   5]
[  1   2 100 100   5]


In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
copy = arr[[0,1]]   # passing list of indexing creates copy not view
print(copy)
copy[(0,1)] = 100
print(copy)
print(arr)

[[1 2 3]
 [4 5 6]]
[[  1 100   3]
 [  4   5   6]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
print(arr.base)

None


In [8]:
print(copy.base)

None


In [ ]:
print(new_arr.base)     # Its a view

[  1   2 100 100   5]
