In [2]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

def square_if_even(x):
    if x % 2 == 0:
        return x**2
    else:
        return x

# print(square_if_even(arr))
# ValueError                                Traceback (most recent call last)
# Cell In[1], line 11
#       8     else:
#       9         return x
# ---> 11 print(square_if_even(arr))

# Cell In[1], line 6
#       5 def square_if_even(x):
# ----> 6     if x % 2 == 0:
#       7         return x**2
#       8     else:

# ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [3]:
vectorized_square_if_even = np.vectorize(square_if_even)
print(vectorized_square_if_even(arr))

[[ 1  4  3]
 [16  5 36]
 [ 7 64  9]]


In [5]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.matmul(arr1,arr2))
print(arr1 @ arr2)

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
